# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm_exploration',
                'doc_host': 'https://ashlsun.github.io',
                'git_url': 'https://github.com/ashlsun/llm_exploration',
                'lib_path': 'llm_exploration'},
  'syms': {'llm_exploration.core': {'llm_exploration.core.foo': ('core.html#foo', 'llm_exploration/core.py')}}}
